{% set name = "perl-config-tiny" %}
{% set version = "2.29" %}
{% set sha256 = "3de79b0ea03a8d6a93e9d9128fe845fb556222b14699a4f6f0d5ca057ae3333b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RS/RSAVAGE/Config-Tiny-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-pathtools
    - perl-test-simple
  run:
    - perl
    - perl-pathtools

test:
  imports:
    - Config::Tiny

about:
  home: http://metacpan.org/pod/Config::Tiny
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: Read/Write .ini style files with as little code as possible
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
    - LICENSE

extra:
  recipe-maintainers:
    - cbrueffer
